### PR TITLE
[REF-2830] server side events and stateless components should not require not require a  backend

### LINKED ISSUE #3295: [REF-2830] rx.color_mode.icon requires a backend, even though it's technically stateless
**Describe the bug**
An otherwise stateless app which uses a color_mode.icon / switch / button makes reflex enable state for the app.

**To Reproduce**
add `rx.color_mode.button()` to a stateless app; it now requires state

**Expected behavior**
Toggling color mode does not require backend state, so it should not make an app stateful and require a backend.

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 0.4.4+
 - OS: 
 - Browser (Optional):

<sub>[REF-2830](https://linear.app/reflex-dev/issue/REF-2830/rxcolor-modeicon-requires-a-backend-even-though-its-technically)</sub>

### PR DESCRIPTION
**Pull request by ElijahAhianyo**
We previously classified anything that uses an eventhandler as stateful. However this is not always true and ended up considering server-side events like `rx.console_log`, etc as stateful when they actually do not require state. With this PR, we make modifications to this logic ensuring that stateless components or server side events arent treated as stateful.

Stateless app
```python
import reflex as rx

def index():
   return rx.vstack(
      rx.button("click to log", on_click=rx.console("log a message")),
      rx.color_mode.button(),
   )
...
```

Stateful app
```python
import reflex as rx

Class State(rx.State):

    def do_something(self):
         ...

def index():
   return rx.vstack(
      rx.button("click ", on_click=State.do_something),
   )
...
```

fixes #3295

### CODE REVIEW

File: reflex/.templates/web/utils/state.js [hunk 1]
```diff
@@ -213,6 +213,10 @@ export const applyEvent = async (event, socket) => {
     return false;
   }
 
+   // Only proceed if the socket is up, otherwise we throw the event into the void
+   if (!socket) {
```
Comment (ElijahAhianyo) [inline reflex/.templates/web/utils/state.js:217]: Delaying/moving the socket check here(as well as in `applyEvent` and `queueEvent`) to allow events that do not necessarily use websockets(think server side events like `rx.console_log`, `rx.window_alert`, etc) but use the event queue to execute.

File: reflex/.templates/web/utils/state.js [hunk 2]
```diff
@@ -273,6 +281,12 @@ export const applyRestEvent = async (event, socket) => {
  * @param socket The socket object to send the event on.
  */
 export const queueEvents = async (events, socket) => {
+
+  // Only proceed if the socket is up, otherwise we throw the event into the void
+  if (!socket) {
```
Comment (ElijahAhianyo) [inline reflex/.templates/web/utils/state.js:286]: for events like `rx.remove_cookie`, `rx.remove_local_storage` that call `queueEvents(initialEvents(), socket)` after to sync with backend state, this shouldn't be an issue since setting them via reflex requires state anyway. I don't expect any repercussions with this. If there're any, don't hesitate to let me know.

File: reflex/.templates/web/utils/state.js [hunk 3]
```diff
@@ -116,6 +128,20 @@ export const applyDelta = (state, delta) => {
...
 };
 
+/**
+ * Only Queue and process events when websocket connection exists.
+ * @param event The event to queue.
+ * @param socket The socket object to send the event on.
+ *
+ * @returns Adds event to queue and processes it if websocket exits, does nothing otherwise.
+ */
+export const queueEventIfSocketExists = (events, socket) => {
```
Comment (masenf) [inline reflex/.templates/web/utils/state.js:138]:
```suggestion
export const queueEventIfSocketExists = async (events, socket) => {
```

File: reflex/.templates/web/utils/state.js [hunk 4]
```diff
@@ -116,6 +128,20 @@ export const applyDelta = (state, delta) => {
...
+  if (!socket) {
+    return;
+  }
+  queueEvents(events, socket);
```
Comment (masenf) [inline reflex/.templates/web/utils/state.js:142]:
```suggestion
  await queueEvents(events, socket);
```

**Review by masenf — COMMENTED** [review]
Nice! My only suggestion is to make the `queueEventIfSocketExists` function `async` so it could be awaited like `queueEvents`.

Thanks for adding the test cases

**Comment by masenf** [comment]
do we actually need [9ef8070](https://github.com/reflex-dev/reflex/pull/3475/commits/9ef8070b87f1f4f55c0176fb44ff73cf6fbaa532)? i think the original code just called `queueEvents` without `await`. The spirit of the requested change was to have the _possibility_ to `await queueEventIfSocketExists(...)` and have it also await the internal queue and process steps.

maybe having these client events await the queue is the behavior that we ultimately want, but there could be subtle bugs with 9ef8070 so i think its safer to merge it separately from this change with have better testing.

i like the code at [e74c39c](https://github.com/reflex-dev/reflex/pull/3475/commits/e74c39cb6814770611d375b88a2053f9162c85d1), it looks like maybe the CI got cancelled for it, but lets roll back to that one and merge it if the CI passes

**Comment by ElijahAhianyo** [comment]
> do we actually need [9ef8070](https://github.com/reflex-dev/reflex/pull/3475/commits/9ef8070b87f1f4f55c0176fb44ff73cf6fbaa532)? i think the original code just called `queueEvents` without `await`. The spirit of the requested change was to have the _possibility_ to `await queueEventIfSocketExists(...)` and have it also await the internal queue and process steps.
> 
> maybe having these client events await the queue is the behavior that we ultimately want, but there could be subtle bugs with [9ef8070](https://github.com/reflex-dev/reflex/commit/9ef8070b87f1f4f55c0176fb44ff73cf6fbaa532) so i think its safer to merge it separately from this change with have better testing.
> 
> i like the code at [e74c39c](https://github.com/reflex-dev/reflex/pull/3475/commits/e74c39cb6814770611d375b88a2053f9162c85d1), it looks like maybe the CI got cancelled for it, but lets roll back to that one and merge it if the CI passes

ah got it, that makes sense. Just made a push to revert it

**Review by masenf — APPROVED** [review]
