### PR TITLE
[FIX] Clipboard paste handler binding in dynamically rendered components

### LINKED ISSUE #6032: Bug Report: rx.clipboard paste event handler not binding in rx.dialog when rendered dynamically
# Bug Report: rx.clipboard paste event handler not binding in rx.dialog when rendered dynamically

## Description

The `rx.clipboard` component's `on_paste` event handler does not fire on the first paste event when the component is inside an `rx.dialog` that is rendered dynamically (e.g., through `rx.foreach` or `rx.match`). The handler only starts working after the user types in the text area first.

**Expected behavior:** The `on_paste` handler should fire immediately on the first paste event, just like it does when the same dialog structure is rendered statically.

**Actual behavior:** The first paste bypasses the handler entirely (default browser paste behavior occurs for text). After typing any character in the text area, subsequent paste events are correctly caught by the handler.

**Key finding:** The issue specifically occurs when `rx.clipboard` is inside an `rx.dialog` that is rendered through dynamic patterns. The same clipboard component works fine when rendered statically, even inside a dialog.

## Environment

- Reflex version: 0.8.19
- Python version: 3.12.7
- OS: Linux

### File: `clipboard_bug_demo.py`

```python
import reflex as rx
from typing import List

class StaticClipboardState(rx.State):
    """State for the static component"""
    feedback: str = ""
    image_attachments: List[str] = []

    @rx.event
    def on_paste(self, data: list[tuple[str, str]]):
        print(f"[STATIC] on_paste called with {len(data)} items")
        for mime_type, item in data:
            print(f"[STATIC] Processing: {mime_type}")
            if mime_type.startswith("image/"):
                print(f"[STATIC] Image found, adding to attachments")
                self.image_attachments = self.image_attachments + [item]
                return
        
        print("[STATIC] No image found in paste data")
        return rx.toast.warning("STATIC: Only image attachments are allowed.")

    @rx.event
    def set_feedback(self, feedback: str):
        self.feedback = feedback

    @rx.event
    def remove_image(self, index: int):
        self.image_attachments.pop(index)


class DynamicClipboardState(rx.State):
    """State for the dynamic component"""
    feedback: str = ""
    image_attachments: List[str] = []
    component_type: str = "clipboard_test"

    @rx.event
    def on_paste(self, data: list[tuple[str, str]]):
        print(f"[DYNAMIC] on_paste called with {len(data)} items")
        for mime_type, item in data:
            print(f"[DYNAMIC] Processing: {mime_type}")
            if mime_type.startswith("image/"):
                print(f"[DYNAMIC] Image found, adding to attachments")
                self.image_attachments = self.image_attachments + [item]
                return
        
        print("[DYNAMIC] No image found in paste data")
        return rx.toast.warning("DYNAMIC: Only image attachments are allowed.")

    @rx.event
    def set_feedback(self, feedback: str):
        self.feedback = feedback

    @rx.event
    def remove_image(self, index: int):
        self.image_attachments.pop(index)


def static_clipboard_component() -> rx.Component:
    """This version WORKS correctly - paste fires immediately even in dialog"""
    return rx.box(
        rx.heading("Static Component in Dialog (WORKS)", size="5"),
        rx.text("Click button to open dialog, then paste an image", margin_y="8px"),
        rx.dialog.root(
            rx.dialog.trigger(
                rx.button(
                    "Open Dialog to Test",
                    size="3",
                    variant="surface",
                    color_scheme="green",
                ),
            ),
            rx.dialog.content(
                rx.dialog.title("Static Clipboard in Dialog"),
                rx.flex(
                    rx.text("Paste an image here - works on first paste", margin_y="8px"),
                    rx.clipboard(
                        rx.text_area(
                            value=StaticClipboardState.feedback,
                            rows="10",
                            on_change=StaticClipboardState.set_feedback,
                            placeholder="Paste an image here...",
                        ),
                        on_paste=StaticClipboardState.on_paste.prevent_default,
                    ),
                    rx.hstack(
                        rx.foreach(
                            StaticClipboardState.image_attachments,
                            lambda image, index: rx.flex(
                                rx.image(src=image, height="50px", width="50px"),
                                rx.icon("x", on_click=StaticClipboardState.remove_image(index))
                            )
                        ),
                    ),
                    rx.dialog.close(
                        rx.button("Close", margin_top="8px"),
                    ),
                    direction="column",
                    spacing="3",
                ),
                max_width="500px",
            ),
        ),
        padding="20px",
        border="2px solid green",
    )


def dynamic_clipboard_component() -> rx.Component:
    """This version FAILS - paste doesn't work until after typing when inside a dialog"""
    return rx.box(
        rx.heading("Dynamic Component in Dialog (BROKEN)", size="5"),
        rx.text("Click button to open dialog, then paste an image", margin_y="8px"),
        rx.dialog.root(
            rx.dialog.trigger(
                rx.button(
                    "Open Dialog to Test",
                    size="3",
                    variant="surface",
                    color_scheme="red",
                ),
            ),
            rx.dialog.content(
                rx.dialog.title("Dynamic Clipboard in Dialog"),
                rx.flex(
                    rx.text("Paste an image here - REQUIRES typing first", margin_y="8px"),
                    rx.clipboard(
                        rx.text_area(
                            value=DynamicClipboardState.feedback,
                            rows="10",
                            on_change=DynamicClipboardState.set_feedback,
                            placeholder="Paste an image here...",
                        ),
                        on_paste=DynamicClipboardState.on_paste.prevent_default,
                    ),
                    rx.hstack(
                        rx.foreach(
                            DynamicClipboardState.image_attachments,
                            lambda image, index: rx.flex(
                                rx.image(src=image, height="50px", width="50px"),
                                rx.icon("x", on_click=DynamicClipboardState.remove_image(index))
                            )
                        ),
                    ),
                    rx.dialog.close(
                        rx.button("Close", margin_top="8px"),
                    ),
                    direction="column",
                    spacing="3",
                ),
                max_width="500px",
            ),
        ),
        padding="20px",
        border="2px solid red",
    )


def render_component(component_type: str):
    """Simulates dynamic component rendering"""
    return rx.match(
        component_type,
        ("clipboard_test", dynamic_clipboard_component()),
        rx.fragment(),
    )


def index() -> rx.Component:
    return rx.container(
        rx.vstack(
            rx.heading("rx.clipboard Bug Demonstration", size="7"),
            rx.text("Test by opening each dialog and pasting an image. Check console for [STATIC] vs [DYNAMIC] logs.", margin_bottom="20px"),
            
            # Static version - WORKS
            static_clipboard_component(),
            
            rx.divider(margin_y="20px"),
            
            # Dynamic version - BROKEN
            # This simulates rendering through rx.foreach or rx.match
            rx.foreach(
                [DynamicClipboardState.component_type],
                lambda comp_type: render_component(comp_type)
            ),
            
            spacing="4",
            padding="20px",
        ),
        max_width="800px",
    )


app = rx.App()
app.add_page(index)
```

## Steps to Reproduce

1. Save the code above as `clipboard_bug_demo.py`
2. Run `reflex init` (if needed) and `reflex run`
3. Open the app in a browser
4. Copy an image to your clipboard (screenshot, image file, etc.)

### Test the STATIC component (green border):
5. Click the green "Open Dialog to Test" button
6. In the opened dialog, click in the text area
7. Paste (Ctrl+V or Cmd+V)
8. ✅ **Result:** The image appears immediately, console shows "[STATIC] on_paste called"

### Test the DYNAMIC component (red border):
9. Refresh the page to reset state
10. Click the red "Open Dialog to Test" button
11. In the opened dialog, click in the text area
12. Paste (Ctrl+V or Cmd+V)
13. ❌ **Result:** Image paste does nothing. Console shows NO "[DYNAMIC] on_paste called" message
14. Type any character in the text area
15. Paste again
16. ✅ **Result:** NOW the image appears and console shows "[DYNAMIC] on_paste called"

## Root Cause Analysis

The `rx.clipboard` component's paste event listener is not being properly attached when:
1. The component is inside an `rx.dialog`
2. AND the dialog is rendered through dynamic rendering patterns (`rx.foreach`, `rx.match`, etc.)

The event handler only binds after the first user interaction with the text area (typing). The same dialog structure works perfectly when rendered statically, indicating this is an issue with how event handlers are bound in dynamically rendered dialog content.

## Workarounds Attempted

None of these worked:
- Adding `on_mount` handler to text area
- Adding `on_focus` handler to text area
- Using a `key` prop that changes to force remount
- Wrapping in additional boxes with mount handlers
- Using controlled dialog state
- Explicitly initializing state before render
- Conditional rendering based on initialization flag

## Impact

This prevents building reusable clipboard-enabled dialog components that can be dynamically rendered, which is a common pattern for CMS-driven or configurable UIs. Workarounds like requiring users to type before pasting create a poor user experience.

## Expected Fix

The `rx.clipboard` component should properly bind its event handlers when inside `rx.dialog` components that are rendered dynamically, ensuring the `on_paste` handler fires on the very first paste event just like it does in statically rendered dialogs.

Image

Image

### PR DESCRIPTION
**Pull request by debangshu919**
### Solution
Added a dependency array `[target_ids]` to the second `useEffect` to ensure:
- The effect re-runs when target IDs change.
- Event listeners are properly cleaned up and re-attached.
- For dynamic elements, a `MutationObserver` watches for DOM changes and attaches listeners once targets are available.

### Changes Made
1. Added `[target_ids]` dependency to the listener attachment `useEffect`.
2. Implemented `MutationObserver` to handle elements that don't exist at initial render.
3. Proper cleanup of both observers and event listeners on unmount.

### All Submissions

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/reflex-dev/reflex/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/reflex-dev/reflex/pulls) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### Changes To Core Features

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

### Screenshots
image

> closes #6032

### CODE REVIEW

File: reflex/.templates/web/utils/helpers/paste.js [hunk 1]
```diff
@@ -35,25 +35,70 @@ const handle_paste_data = (clipboardData) =>
...
 
 export default function usePasteHandler(target_ids, event_actions, on_paste) {
-  return useEffect(() => {
+  const onPasteRef = useRef(on_paste);
+  const eventActionsRef = useRef(event_actions);
+
+  useEffect(() => {
+    onPasteRef.current = on_paste;
+    eventActionsRef.current = event_actions;
+  });
```
Comment (masenf) [inline reflex/.templates/web/utils/helpers/paste.js]: Does it make sense to split these effects and use a dependency array here?

```suggestion
  useEffect(() => {
    onPasteRef.current = on_paste;
  }, [on_paste])
  useEffect(() => {
    eventActionsRef.current = event_actions;
  }, [event_actions]);
```

File: reflex/.templates/web/utils/helpers/paste.js [hunk 2]
```diff
@@ -35,25 +35,70 @@ const handle_paste_data = (clipboardData) =>
...
+
+  useEffect(() => {
     const handle_paste = (_ev) => {
-      event_actions.preventDefault && _ev.preventDefault();
-      event_actions.stopPropagation && _ev.stopPropagation();
-      handle_paste_data(_ev.clipboardData).then(on_paste);
+      eventActionsRef.current.preventDefault && _ev.preventDefault();
+      eventActionsRef.current.stopPropagation && _ev.stopPropagation();
+      handle_paste_data(_ev.clipboardData).then(onPasteRef.current);
```
Comment (masenf) [inline reflex/.templates/web/utils/helpers/paste.js]:
```suggestion
      eventActionsRef.current?.preventDefault && _ev.preventDefault();
      eventActionsRef.current?.stopPropagation && _ev.stopPropagation();
      handle_paste_data(_ev.clipboardData).then(onPasteRef.current);
```

bit safer to use null coalescing here

**Review by masenf — DISMISSED** [review]
this is an excellent PR for a very annoying issue that's been around since day zero of the clipboard feature. thanks for your contribution!
