### PR TITLE
check_initialized: skip REFLEX_DIR check for backend only

### LINKED ISSUE #1477: `reflex run --backend-only` should not require `reflex init`
**Describe the bug**
Running the backend should NOT require reflex init (or bun or nvm).

**To Reproduce**

Use the `counter` app from `reflex-examples`, add the following files:

```Dockerfile
FROM python:3.11
COPY . /app
WORKDIR /app
RUN python3 -m pip install -r requirements.txt
CMD reflex run --env prod --backend-only
```

```console
docker build -t counter .
docker run -it counter
```

**Expected behavior**
Expect the backend of the app to run, which doesn't require init, compiling, or bun/nvm.

Instead, it says `Error: The app is not initialized. Run reflex init first.`

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 0.2.3

The issue is introduced by this new check: https://github.com/reflex-dev/reflex/blob/9cbe02e3fe8aa034f544cbc9ca77bbff5142d6f0/reflex/utils/prerequisites.py#L396

### PR DESCRIPTION
**Pull request by masenf**
when running the python backend only, the REFLEX_DIR does not need to exist because there is no bun/nvm dependency for the backend.

fix #1477

adds a test to `in_docker_test_script` that attempts to export the backend only before init, which passes with this fix

### CODE REVIEW

File: integration/init-test/in_docker_test_script.sh [hunk 1]
```diff
@@ -11,4 +11,4 @@ echo "Installing reflex from local repo code"
 cd /reflex-repo
 poetry install
 echo "Running reflex init in test project dir"
-poetry run /bin/bash -c "cd ~/hello && reflex init"
\ No newline at end of file
+poetry run /bin/bash -c "cd ~/hello && reflex init && rm -rf ~/.reflex .web && reflex export --backend-only"
```
Comment (jackie-pc) [inline integration/init-test/in_docker_test_script.sh:14]: The internal logic depends on platform (like windows vs Linux etc.). Would it make sense to also inject this into the example/counter or reflex-web integration tests?  I.e.

Prior to running the normal `reflex init` in those integration tests, just try to `export --backend-only` (and possibly `reflex run --backend-only`?  That way we gain full matrix coverage for this behavior.

**Review by jackie-pc — DISMISSED** [review]
🚢 it!

**Review by picklelo — APPROVED** [review]
